/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-04-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   03-04-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class myclass {
	public myclass() {

	}

	public String getAppVersion() {
		return '1.0.0';
	}

	
	public String getAppVersion2() {
		return '1.0.0';
	}
}
